config/routes.rb
Rails.application.routes.draw do
  root :to => "products#index"
  
  resources :products do
    resources :reviews
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ActiveRecord::Base
  validates :name, :presence => true
  validates :cost, :presence => true
  validates :country_origin, :presence => true

  has_many :reviews

  scope :ordered_by_name, -> { order(name: :asc) }

  scope :three_most_recent, -> { order(created_at: :desc).limit(3)  }

  scope :most_reviews, -> {(
    select("products.id, products.name, products.cost, products.country_origin, count(reviews.id) as reviews_count")
    .joins(:reviews)
    .group("products.id")
    .order("reviews_count DESC")
    .limit(1)
    )}

    scope :search_country, -> (search_country) { where("lower(country_origin) like lower(?)", "%#{search_country}%")}

end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :product, optional: true
  validates :author, :presence => true
  validates_inclusion_of :rating, :in => 1..5
  validates_length_of :content_body, :maximum => 250
  validates_length_of :content_body, :minimum => 50
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.ordered_by_name
    @three_most = Product.three_most_recent
    @one_most = Product.most_reviews
    if params[:search_country] != nil
      @products = Product.search_country(params[:search_country])
    end
  end

  def show
    @product = Product.find(params[:id])

  end
  def new
    @product = Product.new
  end

  def create
     @product = Product.new(product_params)
     if @product.save
       flash[:notice] = "Product successfully added!"
       redirect_to  products_path
     else
       render :new
     end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product= Product.find(params[:id])
    if @product.update(product_params)
      flash[:notice] = "Product successfully updated!"
      redirect_to products_path
    else
      render :edit
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    flash[:notice] = "Product successfully deleted!"
    redirect_to products_path
  end

  private
  def product_params
     params.require(:product).permit(:name, :cost, :country_origin)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def index
    @product = Product.find(params[:product_id])
    @reviews = @product.review.all

  end

  def show
    @review = Review.find(params[:id])
  end

  def new
    @product = Product.find(params[:product_id])
    @review = @product.reviews.new
  end

  def create
    @product = Product.find(params[:product_id])
    @review = @product.reviews.new(review_params)
    if @review.save
      flash[:notice] = "Product successfully added!"
      redirect_to product_path(@review.product)
    else
      render :new
    end
  end

  def edit
    @product = Product.find(params[:product_id])
    @review = Review.find(params[:id])
    render :edit
  end

  def update
   @review = Review.find(params[:id])
   @product = @review.product
    if @review.update(review_params)
      flash[:notice] = "Product successfully updated!"
      redirect_to product_path(@product)
    else
      render 'reviews/edit'
    end
  end

  def destroy
    @product = Product.find(params[:product_id])
    @review = Review.find(params[:id])
    @review.destroy
    flash[:notice] = "Product successfully deleted!"
    redirect_to product_path(@product)
  end

  private
    def review_params
      params.require(:review).permit(:author, :content_body, :rating)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <div class="container">
    <head>
      <title>MarioFood</title>
      <%= csrf_meta_tags %>

      <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    </head><br><br>
    <header>
      <%= form_tag(products_path, :method => "get") do %>
        <%= text_field_tag :search_country, params[:search_country] %>

        <%= submit_tag "Search Country" %>
      <% end %>
    </header>
    <hr>

    <body>
      <div id="alert">
        <%= flash[:alert]  %>
        <%= flash[:notice] %> 
      </div>


      <%= yield %>
    </body>

  </div>
</html>

app/views/products/_form.html.erb
<%= render "layouts/errors", :object => @product %>

<%= form_for @product do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :cost %>
  <%= f.text_field :cost %>

  <%= f.label :country_origin %>
  <%= f.text_field :country_origin %>

  <%= f.submit %>
<% end %>

app/views/products/edit.html.erb
<h1>Edit product</h1>

<%= render "form" %>

app/views/products/index.html.erb
<div class="row">
  <div class="col-3-sm">
    <h3> 3 most recent</h3>
    <ul>
      <% @three_most.each do |product| %>
        <li><%= link_to product.name, product_path(product) %></li>
      <% end %>
    </ul>
  </div>

  <div class="col-3-sm">
    <h1>Products</h1>
    <h3><%= link_to "Add a New Product", new_product_path %></h3>
    <ul>
      <% @products.each do |product| %>
        <li><%= link_to product.name, product_path(product) %> $<%= product.cost %></li><p>Origin: <%= product.country_origin %></p>
      <% end %>
    </ul>
  </div>

  <div class="col-3-sm">
    <h3>Product with most reviews</h3>
    <ul>
      <% @one_most.each do |product| %>
        <li><%= link_to product.name, product_path(product) %></li>
      <% end %>
    </ul>
  </div>
</div>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render "form" %>

app/views/products/show.html.erb
<h1><%= @product.name %></h1>

<% if @product.reviews.any? %>
  <h4>Here are the reviews for this product:</h4>

  <ul>
    <% @product.reviews.each do |review| %>
      <li>
        <%= review.author %> |
        <%= review.content_body %> |
        <%= review.rating %> |
        <%= link_to "Edit", edit_product_review_path(@product, review) %> |
        <%= link_to "Delete", product_review_path(@product, review),
                                 :data => {:confirm => "Are you sure?",
                                                :method => "delete"} %>
      </li>
    <% end %>
  </ul>
<% else %>
  <p>There are no reviews yet!</p>
<% end %>

<p><%= link_to "Add a review", new_product_review_path(@product) %></p>
<p><%= link_to "Delete product", product_path(@product),
                        :data => {:confirm => "Are you sure?",
                                       :method => "delete"} %></p>

<p><%= link_to "Return to products", products_path %></p>

app/views/reviews/_form.html.erb
<%= render "layouts/errors", :object => @review %>

<%= form_for [@product, @review] do |f| %>
  <%= f.label :author %>
  <%= f.text_field :author %>

  <%= f.label :content_body %>
  <%= f.text_field :content_body %>

  <%= f.label :rating %>
  <%= f.text_field :rating %>

  <%= f.submit %>
<% end %>

app/views/reviews/edit.html.erb
<h1>Edit review</h1>

<%= render "form" %>

<p><%= link_to "Return to products", products_path %></p>

app/views/reviews/new.html.erb
<h1>New review for <%= @product.name %> <%= @product.country_origin %></h1>

<%= render 'form' %>

<p><%= link_to "Return to products", products_path %></p>

app/views/reviews/show.html.erb
<h1><%= @review.author %></h1>